# Question 3

Will the code work? Why or why not?

```js
const getUsers = async () => {
  const url = 'https://jsonplaceholder.typicode.com/users';
  const users = await fetch(url).then(r => r.json()).catch((err) => []);
  console.log(users)
  return users;
}
getUsers()
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
Yes, I believe that the provided code will work as the entire `users` operation is asynchronous using the `await` keyword. By using `await` with the fetch call, this ensures that the code waits for the fetch promise to resolve before proceeding. The `.then(r => r.json())` proceeds by parsing the response to JSON, and if an error occurs during the fetch, the `catch()` block will return an empty array. The final result is logged to the console and returned as expected.

# Teacher Feedback